version: '3'
services:
  backend:
    build:
      context: ./backend/refactorit
    container_name: backend_service
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "80:80"
    depends_on:
      - backend
